/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.DoctorDirectory;
import model.Doctor;
import model.*;

/**
 *
 * @author snehal
 */
public class AddDoctor extends javax.swing.JPanel {

    /**
     * Creates new form AddDoctor
     */
    DoctorDirectory doctorlist;
    public AddDoctor(DoctorDirectory doctorlist) {
        initComponents();
        this.doctorlist = doctorlist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdid = new javax.swing.JTextField();
        txtdname = new javax.swing.JTextField();
        txtdage = new javax.swing.JTextField();
        ddob = new com.toedter.calendar.JDateChooser();
        dspecz = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Add Doctor");

        jLabel2.setText("Doctor ID");

        jLabel3.setText("Doctor Name");

        jLabel4.setText("Doctor Age");

        jLabel5.setText("Doctor DOB");

        jLabel6.setText("Doctor Specialization");

        txtdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdidActionPerformed(evt);
            }
        });

        dspecz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MBBS", "BHMS", "BAMS" }));
        dspecz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dspeczActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setText("Save");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdid)
                            .addComponent(txtdname)
                            .addComponent(txtdage)
                            .addComponent(ddob, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(dspecz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtdage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5))
                    .addComponent(ddob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dspecz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(307, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String name = txtdname.getText();
        String id = txtdid.getText();
        int age = Integer.parseInt(txtdage.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dob = sdf.format(ddob.getDate());
        String specz = dspecz.getSelectedItem().toString();
        //String level = txtLevel.getText();
        //String teaminfo = txtTeamInfo.getText();
        //String phno = txtPhno.getText();
        //String email = txtEmail.getText();
        //String title = txtPosTitle.getText();
        
        
        //Check if all fields are filled or not
        if(txtdname.getText().equals("") || 
           txtdid.getText().equals("") ||
           txtdage.getText().equals("") ||
           dob.equals("") || specz.equals("")){
            
        JOptionPane.showMessageDialog(this,"Please fill data in all fields!.");
        return;
        
        
        
        }
        
        
        //check if Doctor Id already present
        for(Doctor p : doctorlist.getDoctorlist())
        {
            if(p.getPersonid().equals(id))
            {
                    
            JOptionPane.showMessageDialog(this,"Username already exists..Please use different User ID!");
            txtdid.setText("");
            return;
            }
            
        }
        
        
        Doctor d = doctorlist.addNewDoctor();
        
        d.setPersonname(name);
        d.setPersonid(id);
        d.setPersonage(age);
        d.setPersondob(dob);
        d.setDspecz(specz);
        
        
        JOptionPane.showMessageDialog(this,"New Doctor added!");
        // Clear all text fields after adding a employee record
        txtdname.setText("");
        txtdid.setText("");
        txtdage.setText("");
        ddob.setDate(null);
        dspecz.setSelectedIndex(0);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dspeczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dspeczActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dspeczActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ddob;
    private javax.swing.JComboBox<String> dspecz;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtdage;
    private javax.swing.JTextField txtdid;
    private javax.swing.JTextField txtdname;
    // End of variables declaration//GEN-END:variables
}
