/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DoctorDirectory;
import model.Patient;
import model.*;

/**
 *
 * @author snehal
 */
public class HADoctor_frame extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_frame
     */
    //DoctorDirectory doctorlist;
    public HADoctor_frame() {
        initComponents();
        //doctorlist = new DoctorDirectory();
        populateTable();
        
        
        int cityArraySize = CityDirectory.getCityinstance().getCitylist().size();
        String[] cityArray = new String[cityArraySize];
        int itr = 0;
        
        for(City city: CityDirectory.getCityinstance().getCitylist()) {
            cityArray[itr++] = city.getCityname();
        }
        
        combocity.setModel(new javax.swing.DefaultComboBoxModel<>(cityArray));
        
        
        
        int communityArraySize = CommunityDirectory.getCommunityinstance().getCommunitylist().size();
        String[] communityArray = new String[communityArraySize];
        int itr1 = 0;
        
        for(Community c: CommunityDirectory.getCommunityinstance().getCommunitylist()) {
            communityArray[itr1++] = c.getCommunityname();
        }
        
        combocommunity.setModel(new javax.swing.DefaultComboBoxModel<>(communityArray));
        
        
        int hosArraySize = HospitalDirectory.getHospinstance().getHospitallist().size();
        String[] hosArray = new String[hosArraySize];
        int itr2 = 0;
        
        for(Hospital c: HospitalDirectory.getHospinstance().getHospitallist()) {
            hosArray[itr2++] = c.getHospitalname();
        }
        
        combohosp.setModel(new javax.swing.DefaultComboBoxModel<>(hosArray));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdid = new javax.swing.JTextField();
        txtdname = new javax.swing.JTextField();
        txtdage = new javax.swing.JTextField();
        dspecz = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctortable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        lbliderror = new javax.swing.JLabel();
        lblnameerror = new javax.swing.JLabel();
        lblageerror = new javax.swing.JLabel();
        combocity = new javax.swing.JComboBox<>();
        combocommunity = new javax.swing.JComboBox<>();
        combohosp = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        dpass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add Doctor");

        jLabel4.setText("Doctor Age");

        jLabel6.setText("Doctor Specialization");

        txtdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdidActionPerformed(evt);
            }
        });
        txtdid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdidKeyReleased(evt);
            }
        });

        txtdname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdnameKeyReleased(evt);
            }
        });

        txtdage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdageKeyReleased(evt);
            }
        });

        dspecz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MBBS", "BHMS", "BAMS" }));
        dspecz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dspeczActionPerformed(evt);
            }
        });

        jButton1.setText("Create");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Doctor ID");

        jLabel3.setText("Doctor Name");

        doctortable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor ID", "Doctor Name", "Doctor Age", "Doctor Specz"
            }
        ));
        doctortable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctortableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doctortable);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("City");

        jLabel7.setText("Community");

        jLabel8.setText("Hospital");

        jButton5.setText("BACK");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        lbliderror.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lbliderror.setForeground(new java.awt.Color(255, 51, 51));

        lblnameerror.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblnameerror.setForeground(new java.awt.Color(255, 51, 51));

        lblageerror.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblageerror.setForeground(new java.awt.Color(255, 51, 51));

        combocity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combocommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combohosp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbliderror)
                    .addComponent(txtdage)
                    .addComponent(txtdid)
                    .addComponent(txtdname)
                    .addComponent(dspecz, 0, 165, Short.MAX_VALUE)
                    .addComponent(lblnameerror)
                    .addComponent(lblageerror)
                    .addComponent(combocity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combocommunity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combohosp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dpass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbliderror)
                .addGap(35, 35, 35)
                .addComponent(lblnameerror)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dspecz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtdage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblageerror)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(combocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(combocommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(combohosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdidActionPerformed

    private void dspeczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dspeczActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dspeczActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String name = txtdname.getText();
        String id = txtdid.getText();
        int age = Integer.parseInt(txtdage.getText());
        //SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //String dob = sdf.format(ddob.getDate());
        String specz = dspecz.getSelectedItem().toString();
        String dcity = combocity.getSelectedItem().toString();
        String dcommunity = combocommunity.getSelectedItem().toString();
        String dhos = combohosp.getSelectedItem().toString();
        String dpas = dpass.getText();
        //String teaminfo = txtTeamInfo.getText();
        //String phno = txtPhno.getText();
        //String email = txtEmail.getText();
        //String title = txtPosTitle.getText();

        //Check if all fields are filled or not
        if(txtdname.getText().equals("") ||
            txtdid.getText().equals("") ||
            txtdage.getText().equals("") ||
            //dob.equals("") || 
                specz.equals("")){

            JOptionPane.showMessageDialog(this,"Please fill data in all fields!.");
            return;

        }

        //check if Doctor Id already present
        for(Doctor p : DoctorDirectory.getDoctorinstance().getDoctorlist())
        {
            if(p.getPersonid().equals(id))
            {
                JOptionPane.showMessageDialog(this,"Username already exists..Please use different User ID!");
                txtdid.setText("");
                return;
            }

        }

        Doctor d = new Doctor(id,name,age,dpas,specz,dcity,dcommunity,dhos);
        DoctorDirectory.getDoctorinstance().addNewDoctor(d);
        //d.setPersonname(name);
        //d.setPersonid(id);
        //d.setPersonage(age);
        //d.setPersondob(dob);
        //d.setDspecz(specz);

        JOptionPane.showMessageDialog(this,"New Doctor added!");
        // Clear all text fields after adding a employee record
        txtdname.setText("");
        txtdid.setText("");
        txtdage.setText("");
        //ddob.setDate(null);
        combohosp.setSelectedIndex(0);
        combocommunity.setSelectedIndex(0);
        combocity.setSelectedIndex(0);
        
        dspecz.setSelectedIndex(0);
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel tblmodel = (DefaultTableModel) doctortable.getModel();
        if(doctortable.getSelectedRowCount()==1){

            String name = txtdname.getText();
            String empid = txtdid.getText();
            String age = txtdage.getText();
            String Dspecz = dspecz.getSelectedItem().toString();

            tblmodel.setValueAt(name, doctortable.getSelectedRow(), 0);
            tblmodel.setValueAt(empid, doctortable.getSelectedRow(), 1);
            tblmodel.setValueAt(age, doctortable.getSelectedRow(), 3);
            tblmodel.setValueAt(Dspecz, doctortable.getSelectedRow(), 2);

            for(Doctor e : DoctorDirectory.getDoctorinstance().getDoctorlist()){

                if(e.getPersonid().equals(empid)){
                    e.setPersonname(name);
                    e.setPersonage(Integer.parseInt(age));
                    e.setDspecz(Dspecz);

                }
            }
            JOptionPane.showMessageDialog(this,"Doctor record updated successfully!!.");
        }
        else{
            if(doctortable.getRowCount()==0){
                //if table is empty
                JOptionPane.showMessageDialog(this,"Table is empty.");
            }
            else{
                //if row is not selected or multiple row are selected
                JOptionPane.showMessageDialog(this,"Please select a single doctor record to update");
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void doctortableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctortableMouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel tblmodel = (DefaultTableModel) doctortable.getModel();
        
        String tblid = tblmodel.getValueAt(doctortable.getSelectedRow(),0).toString();
        String tblname = tblmodel.getValueAt(doctortable.getSelectedRow(),1).toString();
        String tblspecz = tblmodel.getValueAt(doctortable.getSelectedRow(),2).toString();
        String tblage = tblmodel.getValueAt(doctortable.getSelectedRow(),3).toString();
        //SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //String dob = sdf.format(pdob.getDate());
        //String tbldob = tblmodel.getValueAt(jTable1.getSelectedRow(),3).toString();

        txtdname.setText(tblname);
        txtdid.setText(tblid);
        txtdage.setText(tblage);
        dspecz.setSelectedItem(tblspecz);
        
        //dob.setDate(tbldob);
    }//GEN-LAST:event_doctortableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:


        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtdidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdidKeyReleased
        // TODO add your handling code here:
        
        
        String pattern = "^[a-zA-Z0-9]{0,30}$";
        Pattern pat = Pattern.compile(pattern);
        Matcher match = pat.matcher(txtdid.getText());
        if(!match.matches()){
            lbliderror.setText("ID is incorrect. Please enter characters or numbers.");
        }
        else
        {
            lbliderror.setText(null);
        }
    }//GEN-LAST:event_txtdidKeyReleased

    private void txtdnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdnameKeyReleased
        // TODO add your handling code here:
        
         String pattern = "^[a-zA-Z]{0,30}$";
        Pattern pat = Pattern.compile(pattern);
        Matcher match = pat.matcher(txtdname.getText());
        if(!match.matches()){
            lblnameerror.setText("Name is incorrect. Please enter only characters.");
        }
        else{
            lblnameerror.setText(null);
        }
        
        
        
    }//GEN-LAST:event_txtdnameKeyReleased

    private void txtdageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdageKeyReleased
        // TODO add your handling code here:
          String pattern = "^[0-9]{0,3}$";
        Pattern pat = Pattern.compile(pattern);
        Matcher match = pat.matcher(txtdage.getText());
        if(!match.matches()){
            lblageerror.setText("Age is incorrect. Please enter max 3 digits only");
        }
        else{
            lblageerror.setText(null);
        }
        
        
    }//GEN-LAST:event_txtdageKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HADoctor_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HADoctor_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HADoctor_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HADoctor_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HADoctor_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combocity;
    private javax.swing.JComboBox<String> combocommunity;
    private javax.swing.JComboBox<String> combohosp;
    private javax.swing.JTable doctortable;
    private javax.swing.JTextField dpass;
    private javax.swing.JComboBox<String> dspecz;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblageerror;
    private javax.swing.JLabel lbliderror;
    private javax.swing.JLabel lblnameerror;
    private javax.swing.JTextField txtdage;
    private javax.swing.JTextField txtdid;
    private javax.swing.JTextField txtdname;
    // End of variables declaration//GEN-END:variables


private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel)doctortable.getModel();
        model.setRowCount(0);
        for(Doctor p : DoctorDirectory.getDoctorinstance().getDoctorlist()){
            Object[] row = new Object[10];
            row[0] = p;
            row[1] = p.getPersonname();
            row[2] = p.getDspecz();
            row[3] = p.getPersonage();
            
            model.addRow(row);
        }
    }


}
